#[toml_cfg::toml_config]
pub struct Config {
    #[default("")]
    receiver_mac: &'static str,
}

fn main() {
    // let _ = embuild::build::CfgArgs::output_propagated("ESP_IDF");
    // let _ = embuild::build::LinkArgs::output_propagated("ESP_IDF")?;

    // Check if the `cfg.toml` file exists and has been filled out.
    if !std::path::Path::new("cfg.toml").exists() {
        panic!("You need to create a `cfg.toml` file with your Wi-Fi credentials! Use `cfg.toml.example` as a template.");
    }

    // The constant `CONFIG` is auto-generated by `toml_config`.
    let app_config = CONFIG;
    if app_config.receiver_mac == "11:22:33:44:55:66" || app_config.receiver_mac == "" {
        panic!("You need to fill out the `receiver_mac` field in `cfg.toml`!");
    }

    println!("Mac address of the receiver: {}", app_config.receiver_mac);

    // Make App_config available as a system environment variable.
    embuild::espidf::sysenv::output();
}
