[build]
# target = "xtensa-esp32s3-espidf"
target = "xtensa-esp32-espidf"

# [target.xtensa-esp32s3-espidf]
[target.xtensa-esp32-espidf]
linker = "ldproxy"
# runner = "espflash --monitor" # Select this runner for espflash v1.x.x
# runner = "espflash flash --monitor -T target/xtensa-esp32s3-espidf/release/partition-table.bin" # Select this runner for espflash v2.x.x
runner = "espflash flash --monitor"
rustflags = [ "--cfg",  "espidf_time64"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[unstable]
build-std = ["std", "panic_abort"]

[env]
# MCU="esp32s3"
MCU="esp32"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.1.3"

# Workaround for https://github.com/esp-rs/esp-idf-template/issues/174 until
# https://github.com/esp-rs/esp-idf-hal/pull/387 gets released and the template
# updated.
CRATE_CC_NO_DEFAULTS = "1"

[patch."https://github.com/esp-rs/esp-idf-hal.git"]
# esp-idf-hal = { path = "/Users/junkei/Documents/rust_embedded_projects/esp-idf-hal" }
esp-idf-hal = { git = "https://github.com/junkei-okinawa/esp-idf-hal.git", branch = "custom-gpio-for-M5UnitCam" }

[dependencies]
log = { version = "0.4", default-features = false }
anyhow = "1.0"
esp-idf-svc = { version = "0.49.1", default-features = false, features = [
    "binstart",
    "std",
] }
esp-idf-sys = "0.35"
embedded-svc = "0.28"

esp-camera-rs = { path = "/Users/junkei/Documents/esp_learning/esp-camera-rs2" }

