[build]
target = "riscv32imc-esp-espidf" # ターゲットをesp32c3用に変更

[target.riscv32imc-esp-espidf] # セクション名を変更
linker = "ldproxy"
runner = "espflash flash --monitor" # `--port` はコマンドラインで指定
# rustflags = [ "--cfg",  "espidf_time64"] # esp32c3では不要な場合があるためコメントアウト

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32c3" # MCUをesp32c3に変更
ESP_IDF_VERSION = "v5.1.3"
CRATE_CC_NO_DEFAULTS = "1"

# 受信側には不要なpatchセクションは削除
# [patch."https://github.com/esp-rs/esp-idf-hal.git"]
# esp-idf-hal = { git = "https://github.com/junkei-okinawa/esp-idf-hal.git", branch = "custom-gpio-for-M5UnitCam" }

# 受信側には不要なdependenciesセクションは削除 (Cargo.tomlで管理)